package com.osrapi.models.ff;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "command", schema = "ff")
public final class FFCommandEntity {
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "command_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
            generator = "command_seq")
    @SequenceGenerator(
            name = "command_seq",
            sequenceName = "ff.command_id_seq",
            allocationSize = 1)
    private Long id;
    /** the name. */
    @Column(name = "name")
    @JsonProperty("name")
    @NotNull
    private String name;
    /** the sortOrder. */
    @Column(name = "sort_order")
    @JsonProperty("sort_order")
    @NotNull
    private long sortOrder;
    /** Creates a new instance of {@link FFCommandEntity}. */
    public FFCommandEntity() {
        super();
    }

    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }
    /**
     * Gets the name.
     * @return {@link String}
     */
    public String getName() {
        return name;
    }
    /**
     * Gets the sortOrder.
     * @return {@link long}
     */
    public long getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }
    /**
     * Sets the name.
     * @param val the new value
     */
    public void setName(final String val) {
        name = val;
    }
    /**
     * Sets the sortOrder.
     * @param val the new value
     */
    public void setSortOrder(final long val) {
        sortOrder = val;
    }

}
