package com.osrapi.models.ff;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "hexagon", schema = "ff")
public final class FFHexagonEntity {
    /** the flat. */
    @Column(name = "flat")
    @JsonProperty("flat")
    @NotNull
    private Boolean flat;
    /** the height. */
    @Column(name = "height")
    @JsonProperty("height")
    @NotNull
    private float height;
    /** the horizontalDistance. */
    @Column(name = "horizontal_distance")
    @JsonProperty("horizontal_distance")
    @NotNull
    private float horizontalDistance;
    /**
     * the primary key - an autogenerated id (unique for each user in the db).
     */
    @Id
    @Column(name = "hexagon_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
            generator = "hexagon_seq")
    @SequenceGenerator(
            name = "hexagon_seq",
            sequenceName = "ff.hexagon_id_seq",
            allocationSize = 1)
    private Long id;

    /** the size. */
    @Column(name = "size")
    @JsonProperty("size")
    @NotNull
    private float size;
    /** the verticalDistance. */
    @Column(name = "vertical_distance")
    @JsonProperty("vertical_distance")
    @NotNull
    private float verticalDistance;
    /** the width. */
    @Column(name = "width")
    @JsonProperty("width")
    @NotNull
    private float width;

    /** the x. */
    @Column(name = "x")
    @JsonProperty("x")
    @NotNull
    private long x;
    /** the y. */
    @Column(name = "y")
    @JsonProperty("y")
    @NotNull
    private long y;
    /** the z. */
    @Column(name = "z")
    @JsonProperty("z")
    @NotNull
    private long z;

    /** Creates a new instance of {@link FFHexagonEntity}. */
    public FFHexagonEntity() {
        super();
    }
    /**
     * Gets the flat.
     * @return {@link Boolean}
     */
    public Boolean getFlat() {
        return flat;
    }
    /**
     * Gets the height.
     * @return {@link float}
     */
    public float getHeight() {
        return height;
    }

    /**
     * Gets the horizontalDistance.
     * @return {@link float}
     */
    public float getHorizontalDistance() {
        return horizontalDistance;
    }
    /**
     * Gets the id.
     * @return {@link Long}
     */
    public Long getId() {
        return id;
    }
    /**
     * Gets the size.
     * @return {@link float}
     */
    public float getSize() {
        return size;
    }

    /**
     * Gets the verticalDistance.
     * @return {@link float}
     */
    public float getVerticalDistance() {
        return verticalDistance;
    }
    /**
     * Gets the width.
     * @return {@link float}
     */
    public float getWidth() {
        return width;
    }
    /**
     * Gets the x.
     * @return {@link long}
     */
    public long getX() {
        return x;
    }

    /**
     * Gets the y.
     * @return {@link long}
     */
    public long getY() {
        return y;
    }
    /**
     * Gets the z.
     * @return {@link long}
     */
    public long getZ() {
        return z;
    }
    /**
     * Sets the flat.
     * @param val the new value
     */
    public void setFlat(final Boolean val) {
        flat = val;
    }

    /**
     * Sets the height.
     * @param val the new value
     */
    public void setHeight(final float val) {
        height = val;
    }
    /**
     * Sets the horizontalDistance.
     * @param val the new value
     */
    public void setHorizontalDistance(final float val) {
        horizontalDistance = val;
    }
    /**
     * Sets the id.
     * @param val the new value
     */
    public void setId(final Long val) {
        id = val;
    }

    /**
     * Sets the size.
     * @param val the new value
     */
    public void setSize(final float val) {
        size = val;
    }
    /**
     * Sets the verticalDistance.
     * @param val the new value
     */
    public void setVerticalDistance(final float val) {
        verticalDistance = val;
    }
    /**
     * Sets the width.
     * @param val the new value
     */
    public void setWidth(final float val) {
        width = val;
    }

    /**
     * Sets the x.
     * @param val the new value
     */
    public void setX(final long val) {
        x = val;
    }
    /**
     * Sets the y.
     * @param val the new value
     */
    public void setY(final long val) {
        y = val;
    }
    /**
     * Sets the z.
     * @param val the new value
     */
    public void setZ(final long val) {
        z = val;
    }

}
